### ISSUE TITLE
nice! didn't you run into rough.js problems with size?

### ISSUE THREAD

**Issue by cpryland** [jwilber/roughViz#2]
I've used rough.js in another context, and found that the roughness factor had to be set for each general range of size--for small objects, the roughness was off the charts, and for large minor, all given the same roughness factor.

**Comment by jwilber** [comment]
@cpryland 

Yep! That's an issue. I did add a `roughCeiling` that I apply to every chart (so you can only go so high), but it's still an issue. For example, if you use the `Scatter` class, setting a high roughness will make the circle sizes appear larger than you set. That said, there is something of a trade-off that the user can often play with to minimize this (e.g. in the `Scatter` case, between `radius` and `roughness`).

Maybe I'll change it at some point, or maybe someone will submit a PR. The package is in a very early stage, so there's some other stuff I'd like to improve first!

**Comment by cpryland** [comment]
You're probably safer because people will build charts in a general size range that works, while I had to handle potentially tiny (4px) to huge (2Kpx) objects.

(This is for an Adobe XD plugin which is in limbo for other (XD API bugs) reasons. http://emsoftware.com/xdplugins/rough-draft/.)

**Comment by cpryland** [comment]
Oh, and right, ellipses were more sensitive to roughness than other objects (your circles).

**Comment by jwilber** [comment]
Right. In any case, thanks for the heads up & your plug-in looks awesome :)

**Comment by pshihn** [comment]
@jwilber @cpryland  I would love to hear more thoughts on this (issues and solutions). I have created an issue with possible ways to deal with the 'size' issue. I have noticed it is more pronounced when drawing lines. 
https://github.com/pshihn/rough/issues/114
