### ISSUE TITLE
Different color bars in stacked bar 

### ISSUE THREAD

**Issue by peterbe** [jwilber/roughViz#21]
I messed with [the example](https://blockbuilder.org/jwilber/ee35865631cb805057142568fa5fd090) and changed the data on the 'March' row. I replaced `B` with `D`. (Perhaps March doesn't have a B)
Nothing happened. 
I was expecting the March column (right-most) to have a different color for the `D` value. 

```
data: [
      {month:'Jan', A:20, B: 5,  C: 10},
      {month:'Feb', A:25, B: 10, C: 20},
      {month:'March', A:30, D:50, C:10}
  ],
```

**Comment by peterbe** [comment]
Before changing March's keys:
<img width="730" alt="Screen Shot 2019-11-22 at 5 07 39 PM" src="https://user-images.githubusercontent.com/26739/69463817-bf831000-0d4a-11ea-8f1f-ddb95fca9ccf.png">

After removing the `B:50` and replacing it with `D:50`:
<img width="752" alt="Screen Shot 2019-11-22 at 5 08 13 PM" src="https://user-images.githubusercontent.com/26739/69463838-cad63b80-0d4a-11ea-8ae9-cc7babb09c02.png">

**Comment by jolo-dev** [comment]
@peterbe A valid point.
Do you think in that case it shouldn't be considered at all or should be but marked with a different color because it is a different key?

**Comment by peterbe** [comment]
> @peterbe A valid point.
> Do you think in that case it shouldn't be considered at all or should be but marked with a different color because it is a different key?

Different color. 
How else should I visualize this?
