### ISSUE TITLE
Clickable bar charts

### ISSUE THREAD

**Issue by peterbe** [jwilber/roughViz#22]
I'm using a stacked bar chart and I'd like things to happen when the user clicks bars. At the moment, a legend floats under the mouse cursor but I'd like to do more. I'd click to display information underneath the chart about the bar you clicked on.

**Comment by jwilber** [comment]
That's a solid idea but it's too broad (different users may want different info to display).
I suppose one could add an `additional_info` param to hold an array corresponding in a 1-1 manner for additional data but I think for something so one-off the user is better just cloning the code and adding their own click-event.

**Comment by jwilber** [comment]
Closing for now but if you have any further ideas on it/PR/etc feel free to post (or re-open)! @peterbe
