### ISSUE TITLE
Abstract Class

### ISSUE THREAD

**Issue by jwilber** [jwilber/roughViz#31]
Originally I wanted to create a chart Abstract Base Class with the common methods across the charts (e.g. `resolveFont()`, `initChartValues()`, `setSVG()`, `resolveData()`, etc.) but didn't find a straightforward manner of doing so in ES6. I'm sure it can be done easily enough with prototypal inheritance, but I'd prefer to keep everything as ES6 as possible. 

I don't write too much JavaScript, so it's pretty likely that I missed something. Very open to any ideas!

**Comment by laimonasA** [comment]
I can have a go at refactoring it to just a basic `Chart` class which contains these common methods and possibly some of the shared properties, these other classes will then inherit the methods and properties.
