### ISSUE TITLE
Python Implementation

### ISSUE THREAD

**Issue by charlesdong1991** [jwilber/roughViz#40]
Hello, thanks for making such awesome visualization style. I made a Python wrapper based on your RoughViz

You could check it out here:
https://github.com/charlesdong1991/py-roughviz

And would be appreciated if you'd like to add to your README, so that more people could see and try python version based on your library. ^^

**Comment by jwilber** [comment]
Thanks @charlesdong1991!

There is an existing wrapper here, fyi: https://github.com/hannansatopay/roughviz

I went ahead and added yours to the readme as well :)
