### ISSUE TITLE
A spell error in readme.md

### ISSUE THREAD

**Issue by CNZp** [jwilber/roughViz#41]
like this in 'How to use' chapter:  “biz0” => "bis0"
![wrong1](https://user-images.githubusercontent.com/20235723/71714666-bad17180-2e49-11ea-87d2-da2fa9e648c7.png)
![wrong2](https://user-images.githubusercontent.com/20235723/71714673-c329ac80-2e49-11ea-9187-8d80f1654bfd.png)

**Comment by jwilber** [comment]
Thanks!
