### ISSUE TITLE
Unifiy titleFontSize

### ISSUE THREAD

**Issue by DavidLibeau** [jwilber/roughViz#46]
Some charts have `titleFontSize` with a default value set to `'1rem'` and others set to `'0.95rem'`.
For consistency, I think that all charts should have the same default value.

**Comment by jwilber** [comment]
It's set as follows on charts:

```
style('font-size', (this.titleFontSize === undefined) ?
        `${Math.min(40, Math.min(this.width, this.height) / 5)}px` :
        this.titleFontSize)
```

Not sure where you're getting the `1rem` from?
