### ISSUE TITLE
Deploy a 1.0.7

### ISSUE THREAD

**Issue by slang25** [jwilber/roughViz#54]
First off, I love this library, such a clever idea!

I'm building a website that is still a bit [rough around the edges](https://statsamong.us/#stats/61UknoSW2BTGZLbMV5Tgaj2yyjFsDQU3BwgYxZ8FfEHA), and you can see that the graphs are broken (at the time of writing this), however this is a bug that has already been fixed.

It turns out that the contents of the `dist` folder in the npm package are not up to date, the `src` folder is all good, but there are 2 dist files and neither are more recent than a year.

Would you please consider rebuilding and publishing a `1.0.7`?

Thanks again 🙂

**Comment by jwilber** [comment]
Deployed a V2
