### ISSUE TITLE
Bar chart doesn't work

### ISSUE THREAD

**Issue by mgrigajtis** [jwilber/roughViz#6]
Bar chart doesn't work.

**Comment by jwilber** [comment]
Hey

If you provide a reproducible example I can help you with any issues you’re having. It’s working for my examples + others online, so I suspect it’s something specific to your use-case.

**Comment by mgrigajtis** [comment]
My bad...  I didn't realize the input had to be a CSV or TSV.  I was trying to pass JS arrays into it.
