### ISSUE TITLE
Example links in README are 404

### ISSUE THREAD

**Issue by patrickcameron** [jwilber/roughViz#68]
All “Example” links under the Features section of the readme go to 404 pages.

**Comment by michaeldebetaz** [comment]
They still are. Is the library not maintained anymore ?

I have to say, I do love the art style chosen for the charts 🎨

**Comment by derDere** [comment]
The roughViz repo was edited 3 days ago so I think its still quite active. But apparently the webside used to create the examples (https://blockbuilder.org/) was shut down. so the dev needs to upload those to some other webside. Maybe he could just create a example page hosted on github? Or recreate those examples as a jsfiddle. For now I had to google "roughVis example" and only found a few on codesandbox (https://codesandbox.io/examples/package/rough-viz)

**Comment by derDere** [comment]
If anyone just wants a working readme example here you go:
Bars:    https://jsfiddle.net/derDere/Lbxc8rwv/
HBars:   https://jsfiddle.net/derDere/b0r9egf3/3/
Donut:   https://jsfiddle.net/derDere/b0r9egf3/4/
Line:    https://jsfiddle.net/derDere/b0r9egf3/7/
Pie:     https://jsfiddle.net/derDere/b0r9egf3/9/
Scatter: https://jsfiddle.net/derDere/b0r9egf3/12/

**Comment by jwilber** [comment]
A year on and I've migrated the examples to Observable :) : https://observablehq.com/@jwilber/roughviz-examples
